version: 3

tasks:
  cache:
    cmd: deno cache deps.ts 

  dev:
    deps:
      - cache
    cmd: infisical run --env=dev --path=reliable-handbell --secret-overriding -- deno task start

  env:
    cmds:
      - infisical secrets --path=reliable-handbell {{.CLI_ARGS}}

  img:
    cmds: 
      - docker build -t reliable-handbell .
      - infisical run --env=dev --path=reliable-handbell -- docker run --rm -p 8000:8000 reliable-handbell