version: 3

tasks:
  cache:
    cmd: deno cache deps.ts 

  dev:
    deps:
      - cache
    cmd: deno task start

  img:
    cmds: 
      - docker build -t deno-hono .
      - docker run --rm -p 8000:8000 deno-hono